### ISSUE TITLE
Suggestions?

### ISSUE THREAD

**Issue by nnx0r** [dvLden/Gulp-Tasks#1]
I am open to suggestions and new issues for Hacktoberfest. 
These are Gulp tasks that I am using day to date for simple projects, and there are multiple tasks divided as modules.

**Comment by eduardohiga** [comment]
Hey! Its my first time at Hacktoberfest and im willing to help :). I'm on the first year of Computer Engineering and open to new projects.

**Comment by nnx0r** [comment]
@eduardohiga - Cool man, you are welcome to contribute on any of my projects, including this one.
Please open up an issue if you have any ideas for improvements or fixes. I am open to them...
